apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth
    tier: backend
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        monitor: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
      - name: auth
        image: thanawy/auth-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: web
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: web
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: web
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: auth-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
